# Generated by Django 4.2.6 on 2023-11-02 19:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exchange", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="rate",
            old_name="rate",
            new_name="buy",
        ),
        migrations.AddField(
            model_name="rate",
            name="sell",
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
