# Generated by Django 4.2.6 on 2023-11-07 18:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exchange", "0002_rename_rate_rate_buy_rate_sell"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rate",
            name="buy",
            field=models.DecimalField(decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name="rate",
            name="sell",
            field=models.DecimalField(decimal_places=4, max_digits=10, null=True),
        ),
    ]
