# Generated by Django 4.2.6 on 2023-11-07 18:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exchange", "0003_alter_rate_buy_alter_rate_sell"),
    ]

    operations = [
        migrations.RenameField(
            model_name="rate",
            old_name="currency_from",
            new_name="currency_a",
        ),
        migrations.RenameField(
            model_name="rate",
            old_name="currency_to",
            new_name="currency_b",
        ),
        migrations.AddField(
            model_name="rate",
            name="vendor",
            field=models.CharField(default=0, max_length=55),
            preserve_default=False,
        ),
    ]
