# Generated by Django 4.2.6 on 2023-11-08 09:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exchange", "0004_rename_currency_from_rate_currency_a_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rate",
            name="buy",
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="rate",
            name="sell",
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
